"""align 4B tables with actual columns

Revision ID: 48c61cd161cf
Revises: 97d2bbd8b9f1
Create Date: 2026-09-28 13:16:06.339287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48c61cd161cf'
down_revision = '97d2bbd8b9f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channel_intelligence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_channel', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('avg_order_value', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('avg_basket_size', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('avg_recency', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('finding', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('evidence', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('action', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.String(length=20), nullable=True))
        batch_op.drop_index(batch_op.f('ix_channel_intelligence_channel'))
        batch_op.create_index(batch_op.f('ix_channel_intelligence_preferred_channel'), ['preferred_channel'], unique=True)
        batch_op.drop_column('channel')

    with op.batch_alter_table('dual_pipeline_comparison', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('time_index', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('actual', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('order_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('diff', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('error_pct', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('match', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('explanation', sa.String(length=200), nullable=True))
        batch_op.alter_column('python_prediction',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('spark_prediction',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_dual_pipeline_comparison_record_id'))
        batch_op.drop_column('prediction_diff')
        batch_op.drop_column('spark_probability')
        batch_op.drop_column('match_status')
        batch_op.drop_column('probability_diff')
        batch_op.drop_column('customer_id')
        batch_op.drop_column('python_probability')
        batch_op.drop_column('record_id')
        batch_op.drop_column('actual_class')
        batch_op.drop_column('disagreement_reason')
        batch_op.drop_column('python_correct')
        batch_op.drop_column('spark_correct')

    with op.batch_alter_table('location_intelligence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('menu_item_id', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('location_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_location_quantity', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('min_location_quantity', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('location_gap', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('location_ratio', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('quantity_sold', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('revenue', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('case_type', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('finding', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('evidence', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('action', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.String(length=20), nullable=True))
        batch_op.drop_index(batch_op.f('ix_location_intelligence_item_id'))
        batch_op.create_index(batch_op.f('ix_location_intelligence_menu_item_id'), ['menu_item_id'], unique=False)
        batch_op.drop_column('max_qty_location')
        batch_op.drop_column('best_month')
        batch_op.drop_column('locations_count')
        batch_op.drop_column('min_qty_location')
        batch_op.drop_column('item_id')
        batch_op.drop_column('worst_month')
        batch_op.drop_column('weekend_sales')
        batch_op.drop_column('max_qty')
        batch_op.drop_column('min_qty')
        batch_op.drop_column('weekday_sales')
        batch_op.drop_column('days_available')

    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('menu_item_id', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('item_name', sa.String(length=150), nullable=True))
        batch_op.alter_column('action',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=300),
               existing_nullable=True)
        batch_op.alter_column('priority',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.drop_column('entity_type')
        batch_op.drop_column('evidence_json')
        batch_op.drop_column('model_version')
        batch_op.drop_column('entity_id')

    with op.batch_alter_table('slow_moving_dishes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('menu_item_id', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('category_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('quantity_sold', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('revenue', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('profit_pct', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('wastage_pct', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('promotion_dependency', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('finding', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('evidence', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('action', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.String(length=20), nullable=True))
        batch_op.drop_index(batch_op.f('ix_slow_moving_dishes_item_id'))
        batch_op.create_index(batch_op.f('ix_slow_moving_dishes_menu_item_id'), ['menu_item_id'], unique=False)
        batch_op.drop_column('source_file')
        batch_op.drop_column('total_revenue')
        batch_op.drop_column('item_id')
        batch_op.drop_column('total_quantity')
        batch_op.drop_column('sales_level')

    with op.batch_alter_table('surprise_modification_readiness', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modification', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('parameter', sa.String(length=80), nullable=True))
        batch_op.drop_column('parameter_name')
        batch_op.drop_column('notes')

    with op.batch_alter_table('what_if_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assumption', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('estimate_flag', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('menu_item_id', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('baseline_demand', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('estimated_demand', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('baseline_revenue', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('estimated_revenue', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('baseline_contribution_margin', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('estimated_contribution_margin', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('baseline_wastage_pct', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('estimated_wastage_pct', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('baseline_profitability_pct', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('estimated_profitability_pct', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('revenue_change', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('contribution_margin_change', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('demand_change', sa.Float(), nullable=True))
        batch_op.drop_column('impact_demand')
        batch_op.drop_column('impact_revenue')
        batch_op.drop_column('impact_wastage')
        batch_op.drop_column('impact_margin')
        batch_op.drop_column('item_id')
        batch_op.drop_column('is_estimate')
        batch_op.drop_column('impact_profitability')
        batch_op.drop_column('parameter_change')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('what_if_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parameter_change', sa.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('impact_profitability', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('is_estimate', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('item_id', sa.VARCHAR(length=40), nullable=True))
        batch_op.add_column(sa.Column('impact_margin', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('impact_wastage', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('impact_revenue', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('impact_demand', sa.FLOAT(), nullable=True))
        batch_op.drop_column('demand_change')
        batch_op.drop_column('contribution_margin_change')
        batch_op.drop_column('revenue_change')
        batch_op.drop_column('estimated_profitability_pct')
        batch_op.drop_column('baseline_profitability_pct')
        batch_op.drop_column('estimated_wastage_pct')
        batch_op.drop_column('baseline_wastage_pct')
        batch_op.drop_column('estimated_contribution_margin')
        batch_op.drop_column('baseline_contribution_margin')
        batch_op.drop_column('estimated_revenue')
        batch_op.drop_column('baseline_revenue')
        batch_op.drop_column('estimated_demand')
        batch_op.drop_column('baseline_demand')
        batch_op.drop_column('menu_item_id')
        batch_op.drop_column('estimate_flag')
        batch_op.drop_column('assumption')

    with op.batch_alter_table('surprise_modification_readiness', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('parameter_name', sa.VARCHAR(length=80), nullable=True))
        batch_op.drop_column('parameter')
        batch_op.drop_column('modification')

    with op.batch_alter_table('slow_moving_dishes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sales_level', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('total_quantity', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('item_id', sa.VARCHAR(length=40), nullable=True))
        batch_op.add_column(sa.Column('total_revenue', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('source_file', sa.VARCHAR(length=80), nullable=True))
        batch_op.drop_index(batch_op.f('ix_slow_moving_dishes_menu_item_id'))
        batch_op.create_index(batch_op.f('ix_slow_moving_dishes_item_id'), ['item_id'], unique=False)
        batch_op.drop_column('priority')
        batch_op.drop_column('action')
        batch_op.drop_column('evidence')
        batch_op.drop_column('finding')
        batch_op.drop_column('promotion_dependency')
        batch_op.drop_column('wastage_pct')
        batch_op.drop_column('profit_pct')
        batch_op.drop_column('revenue')
        batch_op.drop_column('quantity_sold')
        batch_op.drop_column('category_name')
        batch_op.drop_column('menu_item_id')

    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entity_id', sa.VARCHAR(length=60), nullable=True))
        batch_op.add_column(sa.Column('model_version', sa.VARCHAR(length=40), nullable=True))
        batch_op.add_column(sa.Column('evidence_json', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('entity_type', sa.VARCHAR(length=40), nullable=True))
        batch_op.alter_column('priority',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('action',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.drop_column('item_name')
        batch_op.drop_column('menu_item_id')
        batch_op.drop_column('source')

    with op.batch_alter_table('location_intelligence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('days_available', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('weekday_sales', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('min_qty', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('max_qty', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('weekend_sales', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('worst_month', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('item_id', sa.VARCHAR(length=40), nullable=True))
        batch_op.add_column(sa.Column('min_qty_location', sa.VARCHAR(length=40), nullable=True))
        batch_op.add_column(sa.Column('locations_count', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('best_month', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('max_qty_location', sa.VARCHAR(length=40), nullable=True))
        batch_op.drop_index(batch_op.f('ix_location_intelligence_menu_item_id'))
        batch_op.create_index(batch_op.f('ix_location_intelligence_item_id'), ['item_id'], unique=False)
        batch_op.drop_column('priority')
        batch_op.drop_column('action')
        batch_op.drop_column('evidence')
        batch_op.drop_column('finding')
        batch_op.drop_column('case_type')
        batch_op.drop_column('revenue')
        batch_op.drop_column('quantity_sold')
        batch_op.drop_column('location_ratio')
        batch_op.drop_column('location_gap')
        batch_op.drop_column('min_location_quantity')
        batch_op.drop_column('max_location_quantity')
        batch_op.drop_column('location_count')
        batch_op.drop_column('menu_item_id')

    with op.batch_alter_table('dual_pipeline_comparison', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spark_correct', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('python_correct', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('disagreement_reason', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('actual_class', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('record_id', sa.VARCHAR(length=60), nullable=True))
        batch_op.add_column(sa.Column('python_probability', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('customer_id', sa.VARCHAR(length=60), nullable=True))
        batch_op.add_column(sa.Column('probability_diff', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('match_status', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('spark_probability', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('prediction_diff', sa.INTEGER(), nullable=True))
        batch_op.create_index(batch_op.f('ix_dual_pipeline_comparison_record_id'), ['record_id'], unique=False)
        batch_op.alter_column('spark_prediction',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('python_prediction',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('explanation')
        batch_op.drop_column('match')
        batch_op.drop_column('error_pct')
        batch_op.drop_column('diff')
        batch_op.drop_column('order_count')
        batch_op.drop_column('actual')
        batch_op.drop_column('time_index')
        batch_op.drop_column('date')

    with op.batch_alter_table('channel_intelligence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('channel', sa.VARCHAR(length=40), nullable=True))
        batch_op.drop_index(batch_op.f('ix_channel_intelligence_preferred_channel'))
        batch_op.create_index(batch_op.f('ix_channel_intelligence_channel'), ['channel'], unique=1)
        batch_op.drop_column('priority')
        batch_op.drop_column('action')
        batch_op.drop_column('evidence')
        batch_op.drop_column('finding')
        batch_op.drop_column('avg_recency')
        batch_op.drop_column('avg_basket_size')
        batch_op.drop_column('avg_order_value')
        batch_op.drop_column('preferred_channel')

    # ### end Alembic commands ###
