"""add 4B output tables

Revision ID: 97d2bbd8b9f1
Revises: d6bc9f017fb3
Create Date: 2026-09-28 13:06:54.811927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97d2bbd8b9f1'
down_revision = 'd6bc9f017fb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_intelligence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=40), nullable=True),
    sa.Column('customers', sa.Integer(), nullable=True),
    sa.Column('orders', sa.Integer(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('channel_intelligence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_channel_intelligence_channel'), ['channel'], unique=True)

    op.create_table('dual_pipeline_comparison',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.String(length=60), nullable=True),
    sa.Column('customer_id', sa.String(length=60), nullable=True),
    sa.Column('actual_class', sa.Integer(), nullable=True),
    sa.Column('spark_prediction', sa.Integer(), nullable=True),
    sa.Column('spark_probability', sa.Float(), nullable=True),
    sa.Column('python_prediction', sa.Integer(), nullable=True),
    sa.Column('python_probability', sa.Float(), nullable=True),
    sa.Column('match_status', sa.String(length=20), nullable=True),
    sa.Column('prediction_diff', sa.Integer(), nullable=True),
    sa.Column('probability_diff', sa.Float(), nullable=True),
    sa.Column('spark_correct', sa.Boolean(), nullable=True),
    sa.Column('python_correct', sa.Boolean(), nullable=True),
    sa.Column('disagreement_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dual_pipeline_comparison', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dual_pipeline_comparison_record_id'), ['record_id'], unique=False)

    op.create_table('location_intelligence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.String(length=40), nullable=True),
    sa.Column('item_name', sa.String(length=150), nullable=True),
    sa.Column('max_qty_location', sa.String(length=40), nullable=True),
    sa.Column('min_qty_location', sa.String(length=40), nullable=True),
    sa.Column('max_qty', sa.Float(), nullable=True),
    sa.Column('min_qty', sa.Float(), nullable=True),
    sa.Column('locations_count', sa.Integer(), nullable=True),
    sa.Column('weekday_sales', sa.Float(), nullable=True),
    sa.Column('weekend_sales', sa.Float(), nullable=True),
    sa.Column('best_month', sa.String(length=20), nullable=True),
    sa.Column('worst_month', sa.String(length=20), nullable=True),
    sa.Column('days_available', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('location_intelligence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_location_intelligence_item_id'), ['item_id'], unique=False)

    op.create_table('slow_moving_dishes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.String(length=40), nullable=True),
    sa.Column('item_name', sa.String(length=150), nullable=True),
    sa.Column('sales_level', sa.String(length=20), nullable=True),
    sa.Column('total_quantity', sa.Float(), nullable=True),
    sa.Column('total_revenue', sa.Float(), nullable=True),
    sa.Column('performance_class', sa.String(length=40), nullable=True),
    sa.Column('source_file', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('slow_moving_dishes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_slow_moving_dishes_item_id'), ['item_id'], unique=False)

    op.create_table('surprise_modification_readiness',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parameter_name', sa.String(length=80), nullable=True),
    sa.Column('current_value', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('what_if_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario', sa.String(length=80), nullable=True),
    sa.Column('item_id', sa.String(length=40), nullable=True),
    sa.Column('item_name', sa.String(length=150), nullable=True),
    sa.Column('parameter_change', sa.String(length=120), nullable=True),
    sa.Column('impact_revenue', sa.Float(), nullable=True),
    sa.Column('impact_margin', sa.Float(), nullable=True),
    sa.Column('impact_demand', sa.Float(), nullable=True),
    sa.Column('impact_wastage', sa.Float(), nullable=True),
    sa.Column('impact_profitability', sa.Float(), nullable=True),
    sa.Column('is_estimate', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('finding', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('evidence', sa.Text(), nullable=True))
        batch_op.alter_column('action',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('evidence_json',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.alter_column('evidence_json',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('action',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
        batch_op.drop_column('evidence')
        batch_op.drop_column('finding')

    op.drop_table('what_if_results')
    op.drop_table('surprise_modification_readiness')
    with op.batch_alter_table('slow_moving_dishes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_slow_moving_dishes_item_id'))

    op.drop_table('slow_moving_dishes')
    with op.batch_alter_table('location_intelligence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_location_intelligence_item_id'))

    op.drop_table('location_intelligence')
    with op.batch_alter_table('dual_pipeline_comparison', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dual_pipeline_comparison_record_id'))

    op.drop_table('dual_pipeline_comparison')
    with op.batch_alter_table('channel_intelligence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_channel_intelligence_channel'))

    op.drop_table('channel_intelligence')
    # ### end Alembic commands ###
